### ISSUE TITLE
The appendix can not be downloaded.

### ISSUE THREAD

**Issue by zylscience** [GRASP-ML/DF-CNN#1]
Hi Lee,
     Thank you for your significant work about lifelong learning.
     But the appendix can not be downloaded in the third authour's personal website, could you please share the appendix with me?

**Comment by leeswon** [comment]
Hi Zhang,

Thank you for your interest on our paper and work. We realized that wrong file is uploaded to the server, so we replaced it with the full paper. The URL in the DF-CNN paper now works correctly  (https://www.seas.upenn.edu/~eeaton/papers/Lee2019Learning.pdf).

Please let us know if you have any questions!
